server {
    server_name saikalyan.website www.saikalyan.website;
    root /var/www/saikalyan.website;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/saikalyan.website/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/saikalyan.website/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    server_tokens off;
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header Referrer-Policy "no-referrer-when-downgrade";
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

}

server {
    if ($host = www.saikalyan.website) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = saikalyan.website) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;
    server_name saikalyan.website www.saikalyan.website;
    return 404; # managed by Certbot




}
